// HSE03297 (Packhouse 11 / IQF 1) and HSE03312 (Packhouse 13 / IQF 2) --
// the master sanitation schedule. Both packhouses run the same schedule
// (same items, tools, chemicals, frequencies), so this one list is shared
// and logged per-factory via MasterCleaningTaskLog.taskKey.
export type CleaningTask = {
  key: string;
  item: string;
  tools: string;
  chemical?: string;
  frequency: string;
};

export type CleaningZone = {
  key: string;
  title: string;
  tasks: CleaningTask[];
};

const STD = "Novaclean Soap 1% / Clint KF200 1% + Clari Chlorine-L 2% / Raed Chlorine 2%";
const CHLORINE_ONLY = "Clari Chlorine-L 2% / Raed Chlorine 2%";
const SOAP_ONLY = "Novaclean Soap 1% / Clint KF200 1%";
const FOAM = "CL2000 Foam / Topaz MD3 (2-5%)";
const DISINFECT = "Fershstart TM Disinfect 1%";
const ROOM_CARE = "Room Care R3";
const LIGHT_TRAPS_FREQ = "1x/week (winter), 2x/week (summer)";

function zone(key: string, title: string, rows: [string, string, string?, string?][]): CleaningZone {
  return {
    key,
    title,
    tasks: rows.map(([item, tools, chemical, frequency], i) => ({
      key: `${key}-${i + 1}`,
      item,
      tools,
      chemical,
      frequency: frequency ?? "Daily",
    })),
  };
}

export const MASTER_CLEANING_SCHEDULE: CleaningZone[] = [
  zone("outside", "Outside the Packhouse", [
    ["Waste Collection", "Broom, Scraper, Brush", undefined, "As needed during the day"],
    ["Plastic Bags", "Manual", undefined, "Daily"],
    ["Waste Bins", "Brush", STD, "Weekly"],
    ["Bollards", "Brush, Cloth, Karcher", STD, "Every 15 days"],
    ["Floors", "Broom, Scraper", undefined, "Daily"],
    ["Walls", "Karcher", STD, "Monthly"],
    ["Electrical Panels & Sockets", "Dry Cloth", undefined, "Monthly"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Crate & Pallet Collection Areas", "Broom, Scraper, Karcher", STD, "Periodic"],
    ["Tanks & Upper Surfaces", "Broom, Brush, Scraper, Squeegee, Cloth, Electric Air Blower", STD, "Biannual"],
    ["Loading Bay Houses", "Broom, Scraper, Brush", undefined, "Daily"],
    ["Loading Bay Houses (Karcher)", "Karcher", undefined, "Weekly"],
    ["Bird Nests", "Ladder, Duster, Gloves", undefined, "Daily"],
    ["Spider Nests", "Ladder, Duster, Gloves", undefined, "Daily"],
    ["Waste Collection Points & Bins", "Broom, Scraper, Karcher", STD, "Daily"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Receiving Tables", "Cloth, Brush", STD, "Periodic"],
    ["Fire Extinguishers & Boxes", "Wet Cloth, Dry Cloth", STD, "Monthly"],
    ["Receiving Room", "Broom, Squeegee, Karcher", STD, "Daily"],
    ["Drains", "Brush, Karcher", STD, "Monthly"],
    ["Rodent Bait Stations", "Brush, Cloth", STD, "Monthly"],
    ["Rodent Bait Stations (Cloth)", "Cloth", undefined, "Weekly"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("transformers", "Transformers & Generators", [
    ["Floors", "Broom, Scraper", undefined, "Daily"],
    ["Doors", "Cloth", undefined, "Daily"],
    ["Walls", "Duster", undefined, "Daily"],
    ["Transformers", "Cloth", undefined, "Daily"],
    ["Generators", "Cloth", undefined, "Daily"],
    ["Fire Extinguisher Boxes", "Cloth", undefined, "Daily"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("water-tanks", "Water Tanks", [
    ["Tanks - Exterior", "Broom, Scraper", undefined, "Daily"],
    ["Tanks - Interior", "Brush, Karcher", STD, "Monthly"],
    ["Pump Room", "Broom, Scraper, Squeegee", STD, "Weekly"],
    ["Water Pipes", "Wet Cloth", STD, "Weekly"],
    ["Pump Room Door", "Cloth", STD, "Weekly"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("pre-cooling", "Inside the Packhouse — Pre-Cooling", [
    ["Floors", "Broom, Scraper, Karcher, Squeegee", STD, "Daily"],
    ["Walls", "Karcher", STD, "Daily"],
    ["Walls + Floors (Foam)", "Foam Machine, Karcher", FOAM, "Weekly"],
    ["Raw Material Dump Tank", "Cloth, Karcher, Brush", SOAP_ONLY, "Daily"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Drains", "Brush, Suction", STD, "Daily"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Light Traps", "Dry Cloth, Ladder", undefined, LIGHT_TRAPS_FREQ],
    ["Pre-Cooling Disinfection", "Disinfection Machine", DISINFECT, "Monthly"],
    ["Fire Extinguishers & Boxes", "Cloth", undefined, "Daily"],
    ["Air Curtains", "Dry Cloth", undefined, "Monthly"],
    ["Plastic Curtains", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Emergency Signs", "Dry Cloth", undefined, "Monthly"],
    ["Electrical Panels & Sockets", "Dry Cloth", undefined, "Monthly"],
    ["Ceilings", "Water Hose, Brush", SOAP_ONLY, "Quarterly"],
    ["Rodent Bait Stations", "Brush, Cloth", STD, "Monthly"],
    ["Rodent Bait Stations (Cloth)", "Cloth", undefined, "Daily"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("operation-hall", "Operation Hall / Freezing Line", [
    ["Floors", "Broom, Scraper, Karcher, Squeegee", STD, "Daily"],
    ["Walls", "Karcher", STD, "Daily"],
    ["Walls + Floors + Lines (Foam)", "Foam Machine, Karcher", FOAM, "Weekly"],
    ["Conveyor Belts", "Water Hose, Cloth, Brush", SOAP_ONLY, "Daily"],
    ["Tables", "Cloth, Brush, Karcher", STD, "Periodic"],
    ["Cutting Machine", "Brush, Water Hose", SOAP_ONLY, "Daily"],
    ["Cutting Machine Blades", "Brush, Water Hose", SOAP_ONLY, "Every 15 days"],
    ["Freezing Hall Disinfection", "Disinfection Machine", DISINFECT, "Monthly"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Emergency Signs", "Dry Cloth", undefined, "Monthly"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Drains", "Brush, Suction", STD, "Daily"],
    ["Waste Bins", "Brush, Water Hose", STD, "Periodic"],
    ["Sorting Bins", "Brush, Water Hose", STD, "Periodic"],
    ["Internal Drainage Channel", "Broom, Scraper, Karcher", STD, "Daily"],
    ["Light Traps", "Dry Cloth, Ladder", undefined, LIGHT_TRAPS_FREQ],
    ["AC Units", "Hand Sprayer", FOAM, "Monthly"],
    ["AC Evaporators", "Cloth", undefined, "Monthly"],
    ["Air Curtains", "Cloth", undefined, "Monthly"],
    ["Plastic Curtains", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Production Lines", "Hand Sprayer", "Alcodes (2-5%)", "Daily"],
    ["Production Lines & Conveyor Belts (Foam)", "Foam Machine, Karcher", "Topaz AC3 (2-5%)", "As needed"],
    ["Regular-Water Wash Basins", "Water Hose, Steel Wool", SOAP_ONLY, "Daily"],
    ["Cold-Water Wash Basins", "Water Hose, Steel Wool", SOAP_ONLY, "Daily"],
    ["Wash-Basin Water Motors", "Dry Cloth", undefined, "Daily"],
    ["Wash/Drinking Water Pipes", "Dry Cloth", undefined, "Weekly"],
    ["Fire-Line Pipes", "Wet Cloth, Dry Cloth", STD, "Weekly"],
    ["Water Chiller - Interior", "Water Hose, Brush", CHLORINE_ONLY, "Weekly"],
    ["Water Chiller - Exterior", "Water Hose", undefined, "Daily"],
    ["Plastic Pallets", "Karcher, Brush", STD, "Daily"],
    ["Product Crates", "Karcher, Brush", STD, "Daily"],
    ["Freezing Tunnel", "Water Hose, Karcher", SOAP_ONLY, "Daily"],
    ["Freezing Tunnel (Foam)", "Water Hose, Karcher", FOAM, "Weekly"],
    ["Ice-Lifting Shovel", "Water Hose, Brush", SOAP_ONLY, "Daily"],
    ["Freezing Tunnel Stairs", "Water Hose, Brush", STD, "Periodic"],
    ["Freezing Tunnel Conveyor Belt", "Water Hose, Brush", SOAP_ONLY, "Every shift"],
    ["Ceilings", "Water Hose, Brush", SOAP_ONLY, "Quarterly"],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["Cable Trays", "Dry Cloth", undefined, "Daily"],
    ["Electrical Panel Covers", "Dry Cloth", undefined, "Daily"],
    ["Electrical Panels & Sockets", "Dry Cloth", undefined, "Monthly"],
    ["Walkway", "Brush, Water Hose", STD, "Daily"],
    ["Foot-Disinfection Basins", "Brush, Water Hose", STD, "Daily"],
    ["Rodent Bait Stations", "Brush, Cloth", STD, "Monthly"],
    ["Rodent Bait Stations (Cloth)", "Cloth", undefined, "Daily"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("packing-area", "Packing Area", [
    ["Floors", "Broom, Scraper, Karcher, Squeegee", STD, "Daily"],
    ["Walls", "Karcher", STD, "Daily"],
    ["Walls + Floors (Foam)", "Foam Machine, Karcher", FOAM, "Weekly"],
    ["Tomra Machine", "Dry Cloth", undefined, "Daily"],
    ["Drains", "Brush, Suction", STD, "Daily"],
    ["Waste Bins", "Brush", STD, "Periodic"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Packing Area Disinfection", "Disinfection Machine", DISINFECT, "Monthly"],
    ["Emergency Signs", "Dry Cloth", undefined, "Monthly"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Packing Tables", "Karcher, Brush, Dry Cloth", SOAP_ONLY, "Daily"],
    ["Metal Detector", "Dry Cloth", undefined, "Daily"],
    ["Carton-Taping Machine", "Dry Cloth", undefined, "Daily"],
    ["Packing Scales", "Dry Cloth", undefined, "Daily"],
    ["Packing Supplies Stands", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Karcher Unit", "Dry Cloth", undefined, "Daily"],
    ["Packing Shovels", "Brush, Dry Cloth", SOAP_ONLY, "Daily"],
    ["Grading Belt", "Brush, Karcher", SOAP_ONLY, "Daily"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["Ceilings", "Water Hose, Brush", SOAP_ONLY, "Quarterly"],
    ["Foot-Disinfection Basins", "Brush, Water Hose", STD, "Daily"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("cold-rooms", "Cold Rooms", [
    ["Floors", "Broom, Scraper, Karcher, Squeegee", STD, "Quarterly"],
    ["Walls", "Karcher", STD, "Quarterly"],
    ["Walls + Floors (Foam)", "Foam Machine, Karcher", FOAM, "Quarterly"],
    ["Cold-Room Corridor", "Broom, Scraper, Karcher, Squeegee", STD, "Daily"],
    ["Cold-Room Cooling Units", "Karcher, Foam Device, Squeegee", FOAM, "Quarterly"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Emergency Signs", "Dry Cloth", undefined, "Monthly"],
    ["Cold-Room Unit/Machine", "Dry Cloth", undefined, "Monthly"],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("loading-rooms", "Loading Rooms", [
    ["Floors", "Broom, Scraper, Karcher", STD, "Daily"],
    ["Walls", "Karcher", STD, "Daily"],
    ["Walls + Floors (Foam)", "Foam Machine, Karcher", FOAM, "Every 15 days"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Loading Dock Plate", "Karcher, Squeegee", STD, "Daily"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("forklift-charging", "Forklift Charging Room", [
    ["Floors", "Broom, Scraper, Karcher, Squeegee", STD, "Daily"],
    ["Walls", "Karcher", STD, "Every 15 days"],
    ["Walls + Floors (Foam)", "Foam Machine, Karcher", FOAM, "Every 15 days"],
    ["Diesel & Electric Forklifts", "Cloth", ROOM_CARE, "Daily"],
    ["Manual Forklift / Pallet Jack", "Wet Cloth, Dry Cloth", SOAP_ONLY, "Daily"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Charging Equipment", "Dry Cloth", undefined, "Daily"],
    ["Fire Extinguishers & Boxes", "Cloth", undefined, "Daily"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("packing-store", "Packing Supplies Store + Double-Door Entry", [
    ["Floors", "Broom, Scraper, Karcher", STD, "Daily"],
    ["Walls", "Duster", undefined, "Monthly"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Waste Bins", "Brush", STD, "Periodic"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Emergency Signs", "Dry Cloth", undefined, "Monthly"],
    ["Storage Shelving", "Dry Cloth", undefined, "Daily"],
    ["Bird Nests", "Ladder, Duster, Gloves", undefined, "Daily"],
    ["Spider Nests", "Ladder, Duster, Gloves", undefined, "Daily"],
    ["Air Curtains", "Dry Cloth", undefined, "Monthly"],
    ["Plastic Curtains", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Light Traps", "Dry Cloth, Ladder", undefined, LIGHT_TRAPS_FREQ],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["Rodent Bait Stations", "Brush, Cloth", STD, "Monthly"],
    ["Rodent Bait Stations (Cloth)", "Cloth", undefined, "Daily"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
  ]),
  zone("maintenance-room", "Maintenance Room", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Weekly"],
    ["Walls", "Duster, Wet Cloth, Dry Cloth", STD, "Monthly"],
    ["Tool Shelves & Cabinets", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("offices", "Offices", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Daily"],
    ["Doors & Windows", "Cloth, Tissues, Cleaner", undefined, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Desks", "Cloth", ROOM_CARE, "Daily"],
    ["Shelves", "Cloth", ROOM_CARE, "Daily"],
    ["Wash Basins", "Brush, Cloth", STD, "Daily"],
    ["Bathrooms", "Squeegee", STD, "Periodic"],
    ["Chairs", "Cloth", undefined, "Daily"],
    ["AC Units", "Dry Cloth", undefined, "Monthly"],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["Waste Bins", "Brush", STD, "Periodic"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
  ]),
  zone("laundry-room", "Laundry Room", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Daily"],
    ["Walls", "Cloth, Duster", STD, "Monthly"],
    ["Washing Machine", "Cloth", ROOM_CARE, "Daily"],
    ["Dryer", "Cloth", ROOM_CARE, "Daily"],
    ["Iron", "Dry Cloth", undefined, "Daily"],
    ["Doors & Windows", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Wash Basin", "Brush", STD, "Daily"],
    ["Scissors / Knives", "Dry Cloth, Brush", "Clari Chlorine-L 250 PPM", "Daily"],
    ["Hangers & Garment Racks", "Cloth", undefined, "Daily"],
    ["Air Extractor Fan", "Dry Cloth", undefined, "Weekly"],
  ]),
  zone("worker-entry", "Employee Entry Area", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Daily"],
    ["Walls", "Karcher", STD, "Daily"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Wash Basins & Taps", "Brush", STD, "Daily"],
    ["Drains", "Brush, Suction", STD, "Daily"],
    ["Waste Bins", "Brush", STD, "Daily"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Soap & Disinfectant Dispensers", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Emergency Signs", "Dry Cloth", undefined, "Monthly"],
    ["CCTV Cameras", "Dry Cloth", undefined, "Weekly"],
    ["Fire Extinguishers & Boxes", "Dry Cloth", undefined, "Daily"],
    ["Hand Dryers", "Cloth", undefined, "Daily"],
    ["Clothing Stands", "Cloth", undefined, "Daily"],
    ["Air Conditioners", "Cloth", undefined, "Daily"],
    ["Water Heaters", "Cloth", undefined, "Daily"],
    ["Drinking-Water Filters", "Cloth", undefined, "Daily"],
  ]),
  zone("dining-halls", "Dining Halls", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Daily"],
    ["Walls", "Broom, Duster, Karcher, Brush", STD, "Weekly"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Dining Tables & Seats", "Brush, Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Emergency Signs", "Dry Cloth", undefined, "Monthly"],
    ["Table Covers", "Brush, Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Waste Bins", "Brush", STD, "Daily"],
    ["Shelves", "Cloth", undefined, "Daily"],
    ["Fire Extinguishers & Boxes", "Cloth", undefined, "Daily"],
    ["Air Extractor Fan", "Dry Cloth", undefined, "Weekly"],
  ]),
  zone("changing-rooms", "Changing Rooms", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Daily"],
    ["Walls", "Wet Cloth, Dry Cloth", STD, "Weekly"],
    ["Doors", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Lockers", "Wet Cloth, Dry Cloth", STD, "Monthly"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Fire Extinguishers & Boxes", "Cloth", undefined, "Daily"],
    ["Aprons / Overalls", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Air Extractor Fan", "Dry Cloth", undefined, "Weekly"],
    ["Waste Bins", "Brush", STD, "Daily"],
  ]),
  zone("bathrooms", "Bathrooms", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Periodic"],
    ["Walls", "Broom, Karcher, Brush", STD, "Daily"],
    ["Toilets & Urinals", "Brush", STD, "Periodic"],
    ["Wash Basins & Taps", "Brush", STD, "Periodic"],
    ["Doors & Windows", "Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Air Extractor Fan", "Dry Cloth", undefined, "Weekly"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
  ]),
  zone("cleaning-equipment", "Cleaning Equipment (Own Tools)", [
    ["Cloths", "—", SOAP_ONLY, "Daily"],
    ["Brushes", "—", STD, "Daily"],
    ["Broom", "—", STD, "Daily"],
    ["Scraper", "—", STD, "Daily"],
    ["Squeegee", "—", STD, "Daily"],
    ["Boot Brush", "—", STD, "Daily"],
    ["Ladder", "Brush, Wet Cloth, Dry Cloth", STD, "Daily"],
    ["Chemical-Prep Suit (Laundered)", "Laundry", "Persil Powder 240g + Chlorine 1%", "Daily"],
    ["Crate-Washing Suit (Laundered)", "Laundry", "Persil Powder 240g + Chlorine 1%", "Daily"],
    ["Duster", "—", STD, "Daily"],
    ["Karcher & Wash Pumps", "Dry Cloth", undefined, "Weekly"],
    ["Hand Sprayer", "—", STD, "Daily"],
    ["Waste Bins (Own)", "Brush, Karcher", STD, "Daily"],
    ["Floor-Cleaning Machine", "Dry Cloth", undefined, "Daily"],
    ["Water Suction Unit", "Cloth, Brush", STD, "Daily"],
  ]),
  zone("cleaning-store", "Cleaning Tools Storage", [
    ["Floors", "Broom, Scraper, Squeegee", STD, "Periodic"],
    ["Walls", "Broom, Karcher, Brush", STD, "Monthly"],
    ["Doors", "—", ROOM_CARE, "Daily"],
    ["Door Frames", "Wet Cloth, Dry Cloth", CHLORINE_ONLY, "Periodic"],
    ["Light Covers", "Dry Cloth, Ladder, Brush", STD, "Quarterly"],
    ["Fire Extinguishers & Boxes", "Cloth", undefined, "Daily"],
    ["Shelves", "Cloth", undefined, "Daily"],
    ["Spill-Containment Basins", "Karcher, Brush, Dry Cloth", STD, "Monthly"],
    ["Post-Maintenance Cleaning", "As required", undefined, "After maintenance"],
  ]),
  zone("smoking-areas", "Smoking Areas", [
    ["Floors & Ashtrays", "Broom, Scraper", undefined, "Daily"],
    ["Fire Extinguishers & Boxes", "Cloth", undefined, "Daily"],
  ]),
];

export const MASTER_CLEANING_TASK_COUNT = MASTER_CLEANING_SCHEDULE.reduce((n, z) => n + z.tasks.length, 0);

export function findCleaningTask(taskKey: string): { zone: CleaningZone; task: CleaningTask } | null {
  for (const z of MASTER_CLEANING_SCHEDULE) {
    const task = z.tasks.find((t) => t.key === taskKey);
    if (task) return { zone: z, task };
  }
  return null;
}
